import Head from 'next/head';
import Image from 'next/image';
import Container from 'react-bootstrap/Container';
import TableView from '../components/Table';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <Container>
      <div className={styles.container}>
        <Head>
          <title>PairWise @Alex_Neo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <TableView />
      </div>
    </Container>
  );
}
